### ISSUE TITLE
Update ReadMe.md

### ISSUE THREAD

**Issue by alphaCoder-69** [alphaCoder-69/ToDo-List#2]

**Comment by gracyashhh** [comment]
Can you assign me this?

**Comment by alphaCoder-69** [comment]
Feel free to work on it man..

**Comment by rAwsam** [comment]
heya can i work on ths

**Comment by gracyashhh** [comment]
Do check my Pull request and let me know if any more changes are needed

**Comment by alphaCoder-69** [comment]
@gracyashhh check your pull request. There are some changes to be done

**Comment by alphaCoder-69** [comment]
@rAwsam sure. Feel free to contribute

**Comment by gracyashhh** [comment]
Changes made @alphaCoder-69

**Comment by gracyashhh** [comment]
Could you also add that hacktoberfest-accepted label lol

**Comment by alphaCoder-69** [comment]
Its done .... @gracyashhh

**Comment by alphaCoder-69** [comment]
Thanks everyone for your contributions
